set.seed(20)
clusters <- kmeans(djiaData[,2:3], 5)
OpenHigh <- as.factor(clusters$cluster)
str(OpenHigh)
OpenHighPlot <- ggplot(djiaData, aes(Open, High, color=djiaData$OpenHigh))+geom_point()
clusters2 <- kmeans(djiaData[,2:4], 5)
OpenLow <- as.factor(clusters2$cluster)
str(OpenLow)
OpenLowPlot <- ggplot(djiaData, aes(Open, Low, color = djiaData$OpenLow))+geom_point()
clusters3 <- kmeans(djiaData[,5:3],5)
CloseHigh <- as.factor(clusters3$cluster)
str(CloseHigh)
CloseHighPlot <- ggplot(djiaData, aes(Close, High, color = djiaData$CloseHigh))+geom_point()
clusters4 <- kmeans(djiaData[,5:4],5)
CloseLow <- as.factor(clusters4$cluster)
str(CloseLow)
CloseLowPlot <- ggplot(djiaData, aes(Close, Low, color = djiaData$CloseLow))+geom_point()